#!/usr/bin/env ruby
require_relative './Exercise2/hand.rb'

if ARGV.length < 5
  STDOUT.puts <<-EOF
  Determines the strength of a given poker hand

  Usage:
    hand As Ad Ah 10c 10h => "As Ad Ah 10c 10h Full House"
  EOF
end

puts Hand.parse(ARGV.join(' ')).to_s
